# {{ ansible_managed }}
version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    restart: "unless-stopped"
    volumes:
      - "prometheus-v2:/prometheus"
      - "{{ westmarches_data_path }}/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090
  grafana:
    image: grafana/grafana
    restart: "unless-stopped"
    volumes:
      - "grafana:/var/lib/grafana"
      - "{{ westmarches_data_path }}/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml"
    environment:
      - "GF_SERVER_DOMAIN={{ foundry_fqdn }}"
      - GF_SERVER_ROOT_URL=https://{{ foundry_fqdn }}/monitoring
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_AUTH_GENERIC_OAUTH_NAME=Discord
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=831107286654910495
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=CFJA6W8uxD9obmc7St0v7KvQCXL0Oisq
      - GF_AUTH_GENERIC_OAUTH_SCOPES=identify email
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://discordapp.com/api/oauth2/authorize
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://discordapp.com/api/oauth2/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://discordapp.com/api/users/@me
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=false
      - GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE=false
    links:
      - prometheus
    ports:
      - 3000
  proxy:
    image: nginx
    restart: "unless-stopped"
    volumes:
      - "{{ westmarches_data_path }}/nginx-custom.conf:/etc/nginx/01-custom.conf.new:ro"
      - "{{ westmarches_data_path }}/nginx-ssl.conf:/etc/nginx/02-ssl.conf.new:ro"
      - "{{ westmarches_data_path }}/nginx-entrypoint.sh:/docker-entrypoint.d/ssl-config.sh:ro"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"
      - "/opt/data/www:/usr/share/nginx/html:ro"
    links:
      - foundry
      - grafana
#      - oauth
    ports:
      - "80:80"
      - "443:443"
#  oauth:
#    image: voucher/vouch-proxy
#    restart: "unless-stopped"
#    ports:
#      - 9090
#    environment:
#      - VOUCH_ALLOWALLUSERS=true
#      - "VOUCH_COOKIE_DOMAIN={{ foundry_domain }}"
#      - "VOUCH_DOMAINS={{ foundry_domain }}"
#      - VOUCH_HEADERS_CLAIMS=id, discriminator, email
#      - OAUTH_PROVIDER=oidc
#      - OAUTH_CLIENT_ID=831107286654910495
#      - OAUTH_CLIENT_SECRET=CFJA6W8uxD9obmc7St0v7KvQCXL0Oisq
#      - "OAUTH_CALLBACK_URL=https://{{ foundry_hostname }}-vouch.{{ foundry_domain }}/auth"
#      - OAUTH_SCOPES=identify, email

volumes:
  prometheus-v2:
  grafana:
