# {{ ansible_managed }}
version: "3.8"

services:
  influxdb:
    image: influxdb:2.0.7
    ports:
      - "8086:8086"
    volumes:
      - "{{ westmarches_data_path }}/influxdb/data:/var/lib/influxdb2"
      - "{{ westmarches_data_path }}/influxdb/config:/etc/influxdb2"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - "DOCKER_INFLUXDB_INIT_PASSWORD={{ INFLUXDB_ADMIN_SECRET }}"
      - DOCKER_INFLUXDB_INIT_ORG=westmarchesdelacave
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket0
      - "DOCKER_INFLUXDB_INIT_ADMIN_TOKEN={{ INFLUXDB_ADMIN_TOKEN }}"
    healthcheck:
      test: curl localhost:8086/health || exit -1
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s
  grafana:
    image: grafana/grafana:8.0.3
    restart: "unless-stopped"
    volumes:
      - "{{ westmarches_data_path }}/grafana/storage:/var/lib/grafana"
      - "{{ westmarches_data_path }}/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml"
      - "{{ westmarches_data_path }}/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yaml"
    environment:
      - "GF_SERVER_DOMAIN={{ foundry_fqdn }}"
      - "GF_SERVER_ROOT_URL=https://{{ foundry_fqdn }}/monitoring"
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_AUTH_GENERIC_OAUTH_NAME=Discord
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - "GF_AUTH_GENERIC_OAUTH_CLIENT_ID={{ OAUTH_CLIENT }}"
      - "GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET={{ OAUTH_SECRET }}"
      - GF_AUTH_GENERIC_OAUTH_SCOPES=identify email
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://discordapp.com/api/oauth2/authorize
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://discordapp.com/api/oauth2/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://discordapp.com/api/users/@me
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=false
      - GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE=false
    links:
      - influxdb
    ports:
      - 3000
    healthcheck:
      test: wget -qO - http://localhost:3000/api/health || exit -1
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s
  proxy:
    image: nginx:1.21.0
    restart: "unless-stopped"
    volumes:
      - "{{ westmarches_data_path }}/nginx-custom.conf:/etc/nginx/01-custom.conf.new:ro"
      - "{{ westmarches_data_path }}/nginx-ssl.conf:/etc/nginx/02-ssl.conf.new:ro"
      - "{{ westmarches_data_path }}/nginx-entrypoint.sh:/docker-entrypoint.d/ssl-config.sh:ro"
      - "{{ westmarches_data_path }}/nextcloud:/opt/data/nextcloud:ro"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"
      - "/opt/data/5etools:/opt/data/5etools:ro"
      - "/opt/data/www:/usr/share/nginx/html:rw"
    links:
      - foundry
      - grafana
      - nextcloud
#      - oauth
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
  manager_api:
    volumes:
      - "{{ westmarches_data_path }}/.env:/opt/.env"
    environment:
      - "BACKUP_S3_ENDPOINT={{ BACKUP_S3_ENDPOINT }}"
      - "AWS_ACCESS_KEY_ID={{ SCW_ACCESS_KEY }}"
      - "AWS_SECRET_ACCESS_KEY={{ SCW_SECRET_KEY }}"
      - "AWS_DEFAULT_REGION={{ SCW_REGION }}"
      - DISCORD_SECRET=${DISCORD_BOT_SECRET}
  foundry:
    environment:
      - "FOUNDRY_AWS_CONFIG=/data/Config/s3config.json"
    volumes:
      - "{{ westmarches_data_path }}/foundry-extensible-plugin:/home/foundry/resources/foundry-extensible-plugin"
    command: [ "--inspect=0.0.0.0:9229", "--loader=/home/foundry/resources/foundry-extensible-plugin/custom-resolver.mjs", "resources/app/main.js", "--port=30000", "--headless", "--noupdate", "--dataPath=/data" ]
  discordbot:
    links:
      - manager_api
    environment:
      - WM_API_SECRET={{ manager_api_secret }}
      - WM_API_ENDPOINT=http://manager_api:5000
      - AWS_ACCESS_KEY_ID={{ DISCORD_AWS_ACCESS_KEY_ID }}
      - AWS_SECRET_ACCESS_KEY={{ DISCORD_AWS_SECRET_KEY }}
      - KANKA_TOKEN={{ KANKA_TOKEN }}
  nextcloud:
    volumes:
      - "{{ nextcloud_data_path }}:/var/www/html:rw"
      - "{{ nextcloud_data_path }}:/opt/data/nextcloud:rw"
#  oauth:
#    image: voucher/vouch-proxy
#    restart: "unless-stopped"
#    ports:
#      - 9090
#    environment:
#      - VOUCH_ALLOWALLUSERS=true
#      - "VOUCH_COOKIE_DOMAIN={{ foundry_domain }}"
#      - "VOUCH_DOMAINS={{ foundry_domain }}"
#      - VOUCH_HEADERS_CLAIMS=id, discriminator, email
#      - OAUTH_PROVIDER=oidc
#      - OAUTH_CLIENT_ID=
#      - OAUTH_CLIENT_SECRET=
#      - "OAUTH_CALLBACK_URL=https://{{ foundry_hostname }}-vouch.{{ foundry_domain }}/auth"
#      - OAUTH_SCOPES=identify, email
