all:
  vars:
    ansible_ssh_user: root
    telegraf_agent_version: 2.0.7
    foundry_docker_image: ishtanzar/wm-docker-foundry:0.7.0
    manager_api_docker_image: ishtanzar/wm-manager-api:0.6.0
    discordbot_docker_image: ishtanzar/wm-discord-speaker:0.6.0
    foundry_extensible_plugin_version: 1.4.3
