all:
  vars:
    ansible_ssh_user: root
    telegraf_agent_version: 2.0.7
    foundry_docker_image: ishtanzar/wm-docker-foundry:2.0.0
    management_api_docker_image: ishtanzar/wm-manager-api:0.6.0
    api_docker_image: ishtanzar/wm-api:0.0.2
    discordbot_docker_image: ishtanzar/wm-discord-bot:0.11.1
    worker_image: ishtanzar/wm-worker:0.0.2
    foundry_extensible_plugin_version: 2.2.0
