all:
  vars:
    ansible_ssh_user: root
    telegraf_agent_version: 2.0.7
    foundry_docker_image: ishtanzar/wm-docker-foundry:2.0.0
    management_api_image: ishtanzar/wm-management-api:0.7.0
    api_image: ishtanzar/wm-api:0.0.2
    discordbot_image: ishtanzar/wm-discord-bot:0.11.1
    worker_image: ishtanzar/wm-worker:0.0.3
    discord_workaround_image: ishtanzar/wm-discord-workaround:0.2.0
    foundry_extensible_plugin_version: 2.3.0
