all:
  vars:
    telegraf_agent_version: "2.0.7"
    docker_compose_version: "1.29.2"
    foundry_version: "9.269"
    grafana_version: "9.4.17"
    influxdb_version: "2.0.7"
    redis_version: "7-alpine"
    meilisearch_version: "v1.5.0"
    foundry_extensible_plugin_version: "3.4.2"

    foundry_docker_image: ishtanzar/wm-docker-foundry:2.3.0
    management_api_image: ishtanzar/wm-management-api:0.13.2
    api_image: ishtanzar/wm-api:1.3.0
    website_image: ishtanzar/wm-website:1.1.2
    discordbot_image: ishtanzar/wm-discord-bot:1.0.0-beta1
    worker_image: ishtanzar/wm-worker:1.0.3
    discord_workaround_image: ishtanzar/wm-discord-workaround:0.4.2
