foundry_data_path: /opt/data/foundry
foundry_hostname: westmarchesdelacave
foundry_domain: ishtanzar.net
foundry_fqdn: "{{ foundry_hostname }}.{{ foundry_domain }}"

westmarches_data_path: /opt/data/westmarches
