foundry_version: 0.7.9
foundryvtt_zip: "foundryvtt-{{ foundry_version }}.zip"
foundry_data_path: /opt/data/foundry
foundry_timezone: Europe/Paris
foundry_language: fr.tidy5e-sheet
foundry_world: west-marches-de-la-cave
foundry_hostname: westmarchesdelacave
foundry_domain: ishtanzar.net
foundry_fqdn: "{{ foundry_hostname }}.{{ foundry_domain }}"
foundry_modules_path: "{{ foundry_data_path }}/Data/modules"

management_api_secret: changeme

nextcloud_fqdn: "nextcloud.{{ foundry_fqdn }}"

foundry_s3_bucket: caveduroliste-westmarches
FOUNDRY_BUCKET_ACCESS_KEY_ID: ''
FOUNDRY_BUCKET_SECRET_ACCESS_KEY: ''
BACKUP_S3_BUCKET: 'backups'
BACKUP_S3_ENDPOINT: ''
