foundryvtt_zip: foundryvtt-0.7.9.zip
foundry_data_path: /opt/data/foundry
foundry_timezone: Europe/Paris
foundry_language: fr.tidy5e-sheet
foundry_world: west-marches-de-la-cave
foundry_hostname: "{{ lookup('env', 'FOUNDRY_HOSTNAME')|default('westmarchesdelacave', True) }}.ishtanzar.net"

s3_bucket: test-bucket-pgmillon
SCW_ACCESS_KEY: ''
SCW_SECRET_KEY: ''
