foundry_hostname: "{{ lookup('env', 'FOUNDRY_HOSTNAME')|default('westmarchesdelacave', True) }}"
foundry_systems:
  - name: dnd5e
    version: 1.2.4
    url: https://gitlab.com/foundrynet/dnd5e/-/archive/release-{version}/dnd5e-release-{version}.zip
    rename: true
